# Teaches kustomize how to substitute cert-manager references.
nameReference:
- kind: Issuer
  group: cert-manager.io
  fieldSpecs:
  - kind: Certificate
    group: cert-manager.io
    path: spec/issuerRef/name

varReference:
- path: spec/dnsNames
  kind: Certificate
  group: cert-manager.io
